server:
  port: 8011
spring:
  application:
    name: res-company
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
  instance:
    preferIpAddress: true
    
feign:
  hystrix:
    enabled: true #默认未false，@FeignClient的fallback